### ISSUE TITLE
Get all transfers a user made

### ISSUE THREAD

**Issue by waldopm** [kevinskyba/kickbase-api-python#8]
Hi,

thanks for this awesome repo. 

Is there a way to get all the transfers a user made?

How did you manage to discover all those endpoints?

Cheers,
Waldo

**Comment by suarephi** [comment]
I pull the feed historically and use that feed as an aggregator. 

curl -X GET -H "Content-Type: application/json" -H "Accept: application/json" -H "Cookie: kkstrauth=[token];" "https://api.kickbase.com/leagues/[league_id]/feed?start=0"

**Comment by waldopm** [comment]
thanks, works for me :)

**Comment by waldopm** [comment]
even better for me is the endpoint with the following filter: {{api_url}}/leagues/{{league_id}}/users/{{user_id}}/feed?filter=12%2C2&start=0
